apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginxargotest
  name: nginx-argo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginxargotest
  template:
    metadata:
      labels:
        app: nginxargotest
    spec:
      containers:
      -  image: nginx
         name: nginxargotest